import svelteParser from "svelte-eslint-parser"
import sveltePlugin from "eslint-plugin-svelte"
import tsParser from "@typescript-eslint/parser"
import tsPlugin from "@typescript-eslint/eslint-plugin"
import prettierPlugin from "eslint-plugin-prettier"
import globals from "globals"

const tsRules = {
	eqeqeq: ["error", "always"],
	indent: "off",
	"no-debugger": "error",
	"no-duplicate-imports": "error",
	"no-implied-eval": "error",
	"no-implicit-coercion": "error",
	"no-new-func": "error",
	"no-prototype-builtins": "error",
	"no-unreachable": "error",
	"no-unused-vars": "off",
	"no-useless-call": "error",
	"no-useless-concat": "error",
	"no-var": "error",
	"no-undef": "off",
	"prefer-const": "error",
	"prefer-object-spread": "error",
	"prefer-regex-literals": "error",
	"prettier/prettier": ["error"],
	"no-return-await": "error",
	"no-throw-literal": "error",
	"no-unneeded-ternary": "error",
	"no-useless-return": "error",
	"prefer-promise-reject-errors": "error",
	"require-await": "error",
	"prefer-template": "error",
	"no-extra-bind": "error",
	"no-useless-escape": "error",
	"no-self-compare": "error",
	"no-console": "off",
	"no-alert": "off",
	"no-shadow": "error",
	"no-constant-condition": ["error", { checkLoops: true }],
	"no-empty": ["error", { allowEmptyCatch: false }],
	"no-extra-semi": "error",
	"no-multi-assign": "error",
	"no-nested-ternary": "error",
	"no-useless-catch": "error",
	"no-useless-rename": "error",
	"prefer-arrow-callback": "error",
	"prefer-rest-params": "error",
	"prefer-spread": "error",

	"@typescript-eslint/await-thenable": "error",
	"@typescript-eslint/consistent-type-definitions": ["error", "type"],
	"@typescript-eslint/consistent-type-imports": "error",
	"@typescript-eslint/explicit-function-return-type": [
		"error",
		{ allowExpressions: true },
	],
	"@typescript-eslint/no-empty-function": "error",
	"@typescript-eslint/no-explicit-any": "error",
	"@typescript-eslint/no-floating-promises": "error",
	"@typescript-eslint/no-inferrable-types": "error",
	"@typescript-eslint/no-misused-promises": "error",
	"@typescript-eslint/no-non-null-assertion": "error",
	"@typescript-eslint/no-unnecessary-condition": [
		"error",
		{ allowConstantLoopConditions: false },
	],
	"@typescript-eslint/no-unnecessary-type-assertion": "error",
	"@typescript-eslint/no-unused-expressions": "error",
	"@typescript-eslint/no-unused-vars": [
		"error",
		{ argsIgnorePattern: "^_" },
	],
	"@typescript-eslint/no-var-requires": "error",
	"@typescript-eslint/strict-boolean-expressions": "error",
	"@typescript-eslint/no-duplicate-enum-values": "error",
	"@typescript-eslint/no-extra-non-null-assertion": "error",
	"@typescript-eslint/no-for-in-array": "error",
	"@typescript-eslint/no-unsafe-assignment": "error",
	"@typescript-eslint/no-unsafe-member-access": "error",
	"@typescript-eslint/no-unsafe-call": "error",
	"@typescript-eslint/no-unsafe-return": "error",
	"@typescript-eslint/restrict-template-expressions": "error",
	"@typescript-eslint/prefer-for-of": "error",
	"@typescript-eslint/prefer-optional-chain": "error",
	"@typescript-eslint/prefer-nullish-coalescing": "error",
	"@typescript-eslint/restrict-plus-operands": "error",
	"@typescript-eslint/unbound-method": "error",
	"@typescript-eslint/array-type": ["error", { default: "array-simple" }],
	"@typescript-eslint/explicit-member-accessibility": [
		"error",
		{ accessibility: "explicit" },
	],
	"@typescript-eslint/no-useless-empty-export": "error",
}

const svelteRules = {
	"svelte/no-at-html-tags": "error",
	"svelte/no-dupe-else-if-blocks": "error",
	"svelte/no-not-function-handler": "error",
	"svelte/no-object-in-text-mustaches": "error",
	"svelte/no-unused-svelte-ignore": "error",
	"svelte/no-useless-mustaches": "error",
	"svelte/require-each-key": "error",
	"svelte/valid-each-key": "error",
	"svelte/no-at-debug-tags": "error",
	"svelte/no-dupe-on-directives": "error",
	"svelte/no-dupe-use-directives": "error",
	"svelte/no-inner-declarations": "error",
	"svelte/no-inspect": "error",
	"svelte/no-target-blank": "error",
	"svelte/no-unused-props": "error",
	"svelte/button-has-type": "error",
	"svelte/infinite-reactive-loop": "error",
	"svelte/no-unnecessary-state-wrap": "error",
	"svelte/prefer-svelte-reactivity": "error",
}

const tsLanguageOptions = {
	parser: tsParser,
	parserOptions: {
		ecmaVersion: "latest",
		sourceType: "module",
		project: ["./tsconfig.app.json"],
		tsconfigRootDir: process.cwd(),
		warnOnUnsupportedTypeScriptVersion: true,
	},
	globals: {
		...globals.browser,
		...globals.es2021,
	},
}

export default [
	{
		files: ["src/**/*.ts"],
		ignores: ["dist/**", "node_modules/**"],
		languageOptions: tsLanguageOptions,
		plugins: {
			"@typescript-eslint": tsPlugin,
			prettier: prettierPlugin,
		},
		rules: tsRules,
	},
	{
		files: ["src/**/*.svelte"],
		ignores: ["dist/**", "node_modules/**"],
		languageOptions: {
			parser: svelteParser,
			parserOptions: {
				parser: tsParser,
				extraFileExtensions: [".svelte"],
				ecmaVersion: "latest",
				sourceType: "module",
				project: ["./tsconfig.app.json"],
				tsconfigRootDir: process.cwd(),
				warnOnUnsupportedTypeScriptVersion: true,
			},
			globals: {
				...globals.browser,
				...globals.es2021,
			},
		},
		plugins: {
			svelte: sveltePlugin,
			"@typescript-eslint": tsPlugin,
			prettier: prettierPlugin,
		},
		rules: {
			...tsRules,
			...svelteRules,
		},
	},
]
